apiVersion: v1
kind: Service
metadata:
  name: floodsight-backend
  namespace: floodsight
  labels:
    app: floodsight
    component: backend
    tier: api
spec:
  type: ClusterIP
  selector:
    app: floodsight
    component: backend
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: floodsight-backend-external
  namespace: floodsight
  labels:
    app: floodsight
    component: backend
    tier: api
  annotations:
    metallb.universe.tf/allow-shared-ip: floodsight
spec:
  type: LoadBalancer
  selector:
    app: floodsight
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  loadBalancerIP: ""  # Let MetalLB assign an IP

